# Generated by Django 3.1.5 on 2024-05-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0029_auto_20240513_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Họ và tên đầy đủ'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Số điện thoại'),
        ),
    ]
