# Generated by Django 3.1.5 on 2024-05-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0031_auto_20240515_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_image',
            field=models.FileField(null=True, upload_to='brand_images'),
        ),
    ]
