# Generated by Django 3.1.5 on 2024-05-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0032_auto_20240515_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='brand_order',
            field=models.IntegerField(null=True),
        ),
    ]
