# Generated by Django 3.1.5 on 2024-05-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0033_brands_brand_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorbikes',
            name='motor_cost',
            field=models.IntegerField(null=True),
        ),
    ]
