# Generated by Django 3.1.5 on 2024-05-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0034_motorbikes_motor_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorbikes',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
