# Generated by Django 3.1.5 on 2024-05-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0035_motorbikes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorbikes',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, null=True),
        ),
    ]
