# Generated by Django 3.1.5 on 2024-05-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0038_auto_20240521_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorbike_features',
            name='feature_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
