# Generated by Django 3.1.5 on 2024-05-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0039_motorbike_features_feature_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_items',
            name='cart',
        ),
        migrations.DeleteModel(
            name='carts',
        ),
    ]
