# Generated by Django 3.1.5 on 2024-05-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0040_auto_20240523_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorbike_specs',
            name='front_layer_sizes',
            field=models.TextField(blank=True, max_length=100, verbose_name='Kích cỡ lốp trước'),
        ),
    ]
