# Generated by Django 3.1.5 on 2024-05-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0041_auto_20240524_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorbike_specs',
            name='compression_ratio',
            field=models.TextField(blank=True, max_length=100, verbose_name='Tỷ số nén'),
        ),
        migrations.AlterField(
            model_name='motorbike_specs',
            name='diameter_plunger_stroke',
            field=models.TextField(blank=True, max_length=100, verbose_name='Đường kính x Hành trình pít tông'),
        ),
        migrations.AlterField(
            model_name='motorbike_specs',
            name='drive_type',
            field=models.TextField(blank=True, max_length=100, verbose_name='Loại truyền động'),
        ),
        migrations.AlterField(
            model_name='motorbike_specs',
            name='engine_type',
            field=models.TextField(blank=True, max_length=100, verbose_name='Loại động cơ'),
        ),
        migrations.AlterField(
            model_name='motorbike_specs',
            name='front_fork',
            field=models.TextField(blank=True, max_length=100, verbose_name='Phuộc trước'),
        ),
        migrations.AlterField(
            model_name='motorbike_specs',
            name='fuel_consumption',
            field=models.TextField(blank=True, max_length=100, verbose_name='Mức tiêu thụ nhiên liệu'),
        ),
        migrations.AlterField(
            model_name='motorbike_specs',
            name='gearbox',
            field=models.TextField(blank=True, max_length=100, verbose_name='Hộp số'),
        ),
        migrations.AlterField(
            model_name='motorbike_specs',
            name='machine_viscosity_capacity',
            field=models.TextField(blank=True, max_length=100, verbose_name='Dung tích nhớt máy'),
        ),
        migrations.AlterField(
            model_name='motorbike_specs',
            name='max_moment',
            field=models.TextField(blank=True, max_length=100, verbose_name='Mô-men xoắn cực đại'),
        ),
        migrations.AlterField(
            model_name='motorbike_specs',
            name='max_power',
            field=models.TextField(blank=True, max_length=100, verbose_name='Công suất tối đa'),
        ),
        migrations.AlterField(
            model_name='motorbike_specs',
            name='rear_fork',
            field=models.TextField(blank=True, max_length=100, verbose_name='Phuộc sau'),
        ),
        migrations.AlterField(
            model_name='motorbike_specs',
            name='rear_layer_sizes',
            field=models.TextField(blank=True, max_length=100, verbose_name='Kích cỡ lốp sau'),
        ),
        migrations.AlterField(
            model_name='motorbike_specs',
            name='start_up_system',
            field=models.TextField(blank=True, max_length=100, verbose_name='Hệ thống khởi động'),
        ),
    ]
