# Generated by Django 3.1.5 on 2024-05-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0043_auto_20240524_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorbike_specs',
            name='front_layer_sizes',
        ),
        migrations.RemoveField(
            model_name='motorbike_specs',
            name='rear_layer_sizes',
        ),
        migrations.AddField(
            model_name='motorbike_specs',
            name='layer_sizes',
            field=models.TextField(blank=True, max_length=100, verbose_name='Kích cỡ lốp trước/sau'),
        ),
        migrations.AlterField(
            model_name='motorbike_specs',
            name='cylinder_capacity',
            field=models.TextField(blank=True, max_length=100, verbose_name='Dung tích xi lanh'),
        ),
        migrations.AlterField(
            model_name='motorbike_specs',
            name='fuel_tank_capacity',
            field=models.TextField(blank=True, max_length=100, verbose_name='Dung tích bình xăng'),
        ),
        migrations.AlterField(
            model_name='motorbike_specs',
            name='ground_clearance',
            field=models.TextField(blank=True, max_length=100, verbose_name='Khoảng sáng gầm xe'),
        ),
        migrations.AlterField(
            model_name='motorbike_specs',
            name='saddle_height',
            field=models.TextField(blank=True, max_length=100, verbose_name='Độ cao yên'),
        ),
        migrations.AlterField(
            model_name='motorbike_specs',
            name='wheel_hub_spacing',
            field=models.TextField(blank=True, max_length=100, verbose_name='Khoảng cách trục bánh xe'),
        ),
    ]
