# Generated by Django 3.1.5 on 2024-05-24 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0044_auto_20240524_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorbike_specs',
            name='motorbike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_test_db.motorbikes', unique=True, verbose_name='Model xe'),
        ),
    ]
