# Generated by Django 3.1.5 on 2024-05-24 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0045_auto_20240524_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_test_db.users', verbose_name='Người mua'),
        ),
    ]
