# Generated by Django 3.1.5 on 2024-05-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0046_cart_items_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(blank=True, choices=[('ordered', 'Ordered'), ('processing', 'Processing'), ('success', 'Success'), ('canceled', 'Canceled')], default='ordered', max_length=20, null=True, verbose_name='Tình trạng')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_test_db.users', verbose_name='Người mua')),
            ],
            options={
                'verbose_name_plural': 'orders',
                'db_table': 'orders',
            },
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='user',
        ),
        migrations.AddField(
            model_name='order_items',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_items',
            name='updated_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='payment_details',
        ),
        migrations.AlterField(
            model_name='order_items',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_test_db.orders'),
        ),
        migrations.DeleteModel(
            name='order_details',
        ),
    ]
