# Generated by Django 3.1.5 on 2024-05-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0047_auto_20240529_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='orders',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='updated_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
