# Generated by Django 3.1.5 on 2024-05-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0048_auto_20240529_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='created_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày tạo đơn hàng'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated_on',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày cập nhật đơn hàng'),
        ),
    ]
