# Generated by Django 3.1.5 on 2024-05-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0051_orders_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ giao hàng'),
        ),
    ]
