# Generated by Django 3.1.5 on 2024-06-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_db', '0052_orders_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorbike_skus',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
